version: '3'

services:
  mysql-standalone:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password1234
      - MYSQL_DATABASE=delivery
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password1234
  springboot-docker-container:
    image: springboot-docker-container
    ports:
       - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone